# Generated by Django 5.1 on 2024-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id_sucursal', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('NumTelefono', models.IntegerField()),
                ('creditos', models.PositiveSmallIntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('Horario', models.CharField(max_length=4)),
            ],
        ),
    ]
